### PR TITLE
Feat/fee test

### PR DESCRIPTION
**Pull request by tobi-bams**

### CODE REVIEW

**Comment by Evanfeenstra** [comment]
why 18 for `time_lock_delta`?

**Comment by tobi-bams** [comment]
> why 18 for `time_lock_delta`?

18 is the minimum, also you can't update channel policy with RPC without updating the time_lock_delta by default it is 0.

Lastly, I built this endpoint for the test majorly.

**Comment by Evanfeenstra** [comment]
@tobi-bams I pushed a docker image `sphinx-proxy:0.1.34-log-fee-limit` with more logs to figure out what the problem is with CLN fees

Can you run that locally and read the sphinx-proxy logs? There should be one log line with `router send:` showing FeeLimitSat/FeeLimitMsat and another with `SEND PAY REQ ` showing CLN Maxfeepercent

**Comment by tobi-bams** [comment]
@Evanfeenstra 
router send: `dest:"\x03d\xc0\\\xbc\xbb\x96\x12\x03l\xc6b\x97DZ\x88\xbc\xfc!\x94\x1f\xd8\x16\xe1zV\xb5K\x0bR\xff\x02\xb9"  amt:200  payment_hash:"䷐|\xf9\xc67W\xcc\x11 \xb4\xcdt\xf9\x81\xcf\x06\xe1\xf6\r\xe8|^P:\xc1\xefi\xc3=\x02"  final_cltv_delta:141  timeout_seconds:16  fee_limit_sat:10  dest_custom_records:{key:133773310  value:"{\"type\":28}rb8zinogj3wgucw4ttgw3iek11k3nni684w7yhtagtf1914ofazgcicor5ca5uoj5g6icp3b8qaejmc31qjffuxeqemf56k3g9hjg5r8"}  dest_custom_records:{key:5482373484  value:"\xe6\x90\xd3\xc9\t\xebJ\x82/\xe21\t\xbe\x1e\xfdy0\n4u\xb8\x13\x04\x16y\x9ee\x81\xc0\xf3\x0e\x8f"}  dest_features:TLV_ONION_OPT`

SEND PAY REQ destination: `"\x03d\xc0\\\xbc\xbb\x96\x12\x03l\xc6b\x97DZ\x88\xbc\xfc!\x94\x1f\xd8\x16\xe1zV\xb5K\x0bR\xff\x02\xb9"  amount_msat:{msat:200000}  label:"705e7a9ca72ae9e053cfcdf31d09fdf3"  extratlvs:{entries:{type:133773310  value:"{\"type\":28}rb8zinogj3wgucw4ttgw3iek11k3nni684w7yhtagtf1914ofazgcicor5ca5uoj5g6icp3b8qaejmc31qjffuxeqemf56k3g9hjg5r8"}}`

I figured that this is trying to pay 200 sats but I am only trying to pay `80sats`

**Comment by tobi-bams** [comment]
router send: `dest:"\x03d\xc0\\\xbc\xbb\x96\x12\x03l\xc6b\x97DZ\x88\xbc\xfc!\x94\x1f\xd8\x16\xe1zV\xb5K\x0bR\xff\x02\xb9"  amt:80  payment_hash:"d\x07\x1dj\x10c}\x11%\x92;\xddE ,\xc8\xf4\xe2\x17\tĈ\x9a\xfe\xdb=[}\xfcA\xc9W"  final_cltv_delta:141  timeout_seconds:16  fee_limit_sat:21  dest_custom_records:{key:133773310  value:"{\"type\":28}rb8zinogj3wgucw4ttgw3iek11k3nni684w7yhtagtf1914ofazgcicor5ca5uoj5g6icp3b8qaejmc31qjffuxeqemf56k3g9hjg5r8"}  dest_custom_records:{key:5482373484  value:"UDK\x19\xbbe\x8fr\xba\xbe?\x0eʻ3O/ e\x84\xab\r\x01\x85\x9e\xf8\x9a\x9c\xca\xf9\x13\xcb"}  dest_features:TLV_ONION_OPT`

SEND PAY REQ `destination:"\x03d\xc0\\\xbc\xbb\x96\x12\x03l\xc6b\x97DZ\x88\xbc\xfc!\x94\x1f\xd8\x16\xe1zV\xb5K\x0bR\xff\x02\xb9"  amount_msat:{msat:80000}  label:"c7190fbcea205eddd358e5f25ae70647"  extratlvs:{entries:{type:133773310  value:"{\"type\":28}rb8zinogj3wgucw4ttgw3iek11k3nni684w7yhtagtf1914ofazgcicor5ca5uoj5g6icp3b8qaejmc31qjffuxeqemf56k3g9hjg5r8"}}`
finalizeRemoteInvoice err rpc error:` code = Unknown desc = Error calling method KeySend: RpcError { code: Some(210), message: "Ran out of routes to try after 2 attempts: see `paystatus`" }`

**Comment by Evanfeenstra** [comment]
@tobi-bams i think i finally found the bug, can you try sphinx-proxy:0.1.34-log-fee-limit-2

**Comment by tobi-bams** [comment]
> @tobi-bams i think i finally found the bug, can you try sphinx-proxy:0.1.34-log-fee-limit-2

This solved it, the test is passing now.

**Pull request merged**
