### PR TITLE
[Security] Updating socketio and also adding testing for socketio

### PR DESCRIPTION
**Pull request by kevkevinpal**

### CODE REVIEW

**Comment by kevkevinpal** [comment]
Still need to add some testing and also see if this is the right approach

I'm following what [socketio is recommending](https://socket.io/docs/v4/migrating-from-2-x-to-3-0/#how-to-upgrade-an-existing-production-deployment)

**Comment by kevkevinpal** [comment]
Not sure if this is a bug but when I do 

`addContact` -> `sendPayment` the order I receive the response from the web socket for bob is first the `sendPayment` then I get the `addContact`

**Comment by kevkevinpal** [comment]
> > Not sure if this is a bug but when I do
> > `addContact` -> `sendPayment` the order I receive the response from the web socket for bob is first the `sendPayment` then I get the `addContact`
> 
> that is strange, not sure what could cause that...

I can open up an issue for this

**Comment by kevkevinpal** [comment]
so far these things have been tested for socketio

Recieve message [message]
Join Group [group_join]
Confirmation [confirmation]
recieve boost [boost]
delete message [delete]
Recive Payment [direct_payment]

More to still be tested

Remaining
        invoice: 2,
    payment: 3,
    cancellation: 4,
    attachment: 6,
    purchase: 7,
    purchase_accept: 8,
    purchase_deny: 9,
    contact_key: 10,
    contact_key_confirmation: 11,
    group_create: 12,
    group_invite: 13,
    group_leave: 15,
    group_kick: 16,
    repayment: 18,
    member_request: 19,
    member_approve: 20,
    member_reject: 21,
    tribe_delete: 22,
    bot_install: 23,
    bot_cmd: 24,
    bot_res: 25,
    heartbeat: 26,
    heartbeat_confirmation: 27,
    keysend: 28, // no e2e
    query: 30,
    query_response: 31,

**Comment by kevkevinpal** [comment]
@Evanfeenstra 
This should be good to go we still need to add some more scenarios to cover where socketio is used in the app but we can add the remaining ones as bounties and since we covered the major one and know that the socketio util is working for them.

Also had Tom test this and it looks good on his end

Remaining

[Looks not used?] payment: 3,
[Looks not used?] cancellation: 4,
purchase_deny: 9,
contact_key: 10,
contact_key_confirmation: 11,
group_create: 12,
group_invite: 13,
group_kick: 16,
repayment: 18,
member_request: 19,
member_approve: 20,
member_reject: 21,
bot_install: 23,
bot_cmd: 24,
bot_res: 25,
heartbeat: 26,
heartbeat_confirmation: 27,
keysend: 28, // no e2e
query: 30,
query_response: 31,

**Comment by Evanfeenstra** [comment]
Awesom @kevkevinpal, thanks for doing thorough tests! Feel free to merge whenever

**Comment by kevkevinpal** [comment]
> Awesom @kevkevinpal, thanks for doing thorough tests! Feel free to merge whenever

sounds good I'll merge and then open up some tickets for some more socket tests

**Pull request merged**
