### PR TITLE
run prettier in github actions

### PR DESCRIPTION
**Pull request by antonilol**
title

~draft pr for now because i dont want this merged before #423 (it will be a pain to rebase that pr with many little changes this produces)~

### CODE REVIEW

**Comment by kevkevinpal** [comment]
is there anyway of running prettier on the PR itself when someone opens to master so the diff is never ugly incase someone auto formats to prettier with their own config?

**Comment by antonilol** [comment]
> is there anyway of running prettier on the PR itself when someone opens to master so the diff is never ugly incase someone auto formats to prettier with their own config?

I tried this with the auto build but it didnt seem to work, even with the "Allow edits from maintainers" setting turned on

**Comment by antonilol** [comment]
just realized i can run prettier on other prs and merged should go fine because both branches contain the same change

**Comment by antonilol** [comment]
rebased + also format `.github/**/*.yml` now

**Comment by antonilol** [comment]
rebased

**Review by kevkevinpal — APPROVED** [review]
This looks good to me

**Pull request merged**
