### PR TITLE
Add optional router and signer macaroon locations

### LINKED ISSUE #177: Macaroon locations
I'm currently integrating Sphinx Relay into the BTCPay Server Docker deployment (see btcpayserver/btcpayserver-docker#458). 

Working on that I noticed that all macaroon are expected to be located in the same folder as the admin.macaroon ([reference](https://github.com/stakwork/sphinx-relay/blob/master/src/utils/macaroon.ts#L8)). This isn't the case for us and we'd like to keep deployed macaroons where they are for backwards compatibility. (LND introduced additional macaroons and moved the files after BTCPay started supporting LND)

Would you accept a PR that introduces optional config (via environment variables and the config json) for the individual macaroon paths? In addition to the existing [`macaroon_location`](https://github.com/stakwork/sphinx-relay/blob/master/src/utils/config.ts#L17) I'd add this then:

```js
router_macaroon_location: ENV.ROUTER_MACAROON_LOCATION || config.router_macaroon_location,
signer_macaroon_location: ENV.SIGNER_MACAROON_LOCATION || config.signer_macaroon_location,
```

### PR DESCRIPTION
**Pull request by dennisreimann**
Closes #177.

I didn't find any tests, let me know if I missed something.

### CODE REVIEW

**Comment by dennisreimann** [comment]
@Evanfeenstra what can I do to move this forward? I'd like to finish the Sphinx Relay integration in BTCPay and need this therefor.

**Comment by Evanfeenstra** [comment]
looks good, thanks @dennisreimann

**Comment by dennisreimann** [comment]
Thanks for merging. Any idea what's going on with the build?

**Comment by Evanfeenstra** [comment]
I built and pushed to master, its working for me. What issue were you seeing?

**Comment by dennisreimann** [comment]
I mean the build that's included here in the PRs on GitHub. Those fail … see also my other PR.

**Comment by dennisreimann** [comment]
Also: What's the reason of including the build files (dist) in the repo instead of publishing a npm package for the releases?

**Comment by dennisreimann** [comment]
@Evanfeenstra When is the next release scheduled? Looking forward to get the integration going :)

**Comment by Evanfeenstra** [comment]
@dennisreimann I just released :) We have a new baby at home so I haven't been workin much!

**Comment by dennisreimann** [comment]
Awesome, congrats and all the best! 🎉

Thanks for the release.

**Comment by dennisreimann** [comment]
@gonzaloaune Can you publish v2.0.12 to Docker hub?

**Comment by gonzaloaune** [comment]
I don't publish them, builds are automatically published when they get merged, I see the last one failed, just tried a re-run and it worked. @Evanfeenstra can we make sure the build succeeds or that alerts you if something goes wrong?

**Pull request merged**
