### PR TITLE
Msg channels

### PR DESCRIPTION
**Pull request by kevkevinpal**
We are trying to add msg channels to sphinx and we have a related PR up in tribes
Related PR
https://github.com/stakwork/sphinx-tribes/pull/164

In this change, we are using the `parent_id` to indicate which channel the message belongs to and then we also have a `tribe_channel` endpoint to create a new channel which then calls the tribes API to store that channel

### CODE REVIEW

**Comment by Evanfeenstra** [comment]
I was thinking the app could call tribes server directly (without proxying thru relay), but i guess this makes more sense actually. This way is following relay's existing conventions

**Comment by kevkevinpal** [comment]
> I was thinking the app could call tribes server directly (without proxying thru relay), but i guess this makes more sense actually. This way is following relay's existing conventions

yea haha I saw you doing it this way previously so I thought it'd be best to follow it, I'll add more testing and then write out a little spec like what we expect as the inputs to the endpoint and what you should expect as a response

**Comment by kevkevinpal** [comment]
> looks like a nice way to write a spec :)
> 
> `owner_pubkey` is removed now though right?

just removed it and pushed new commit for that change [bdec4b3](https://github.com/stakwork/sphinx-relay/pull/294/commits/bdec4b3014f5a1e5c0312f5d3ed923c5a1e1c126)

**Comment by kevkevinpal** [comment]
| Item Desc | Value |
| ----------- | ----------- |
| Endpoint | `/tribe_channel/{channel_id}/?token={token}` |
| Type | DELETE | 
| Description | This endpoint is used to delete a channel in a tribe/groupchat we call the tribes server to update a channel to set its deleted flag to be true |
| Request |  <pre>body: {}</br>headers: {</br>   authToken: string</br>}</pre> |
| Response | <pre>{</br>   success: boolean</br>   response: boolean</br>}</br>|

**Comment by kevkevinpal** [comment]
I've just added an md file in docs for the comments I just posted 

[a3d9e1b](https://github.com/stakwork/sphinx-relay/pull/294/commits/a3d9e1b77b3bb178f30460a7f9529bee32a421aa)
https://github.com/kevkevinpal/sphinx-relay/blob/msg-channels/docs/deep/api.md

**Comment by kevkevinpal** [comment]
So theres something called openapi I think it may be worth checking out

I added a yml  file here [0301db3](https://github.com/stakwork/sphinx-relay/pull/294/commits/0301db3addd24abab3ef9d6bec77b6bafa8124d3)

and here's a link to redoc which uses the openapi format
https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/kevkevinpal/sphinx-relay/msg-channels/docs/deep/openapi.yml&nocors

**Comment by kevkevinpal** [comment]
I think the changes here might be ready we just need to finish the changes for `sphinx-tribes` and then publish a new docker image and the test should work

**Comment by Evanfeenstra** [comment]
> I think the changes here might be ready we just need to finish the changes for `sphinx-tribes` and then publish a new docker image and the test should work

You can build `sphinx-tribes` locally like `docker build --no-cache -t sphinx-tribes .`, then switch the tribes image in `sphinx-stack` to simply `sphinx-tribes`, and run the tests that way. So when we publish images we know everything is good

**Comment by kevkevinpal** [comment]
> > I think the changes here might be ready we just need to finish the changes for `sphinx-tribes` and then publish a new docker image and the test should work
> 
> You can build `sphinx-tribes` locally like `docker build --no-cache -t sphinx-tribes .`, then switch the tribes image in `sphinx-stack` to simply `sphinx-tribes`, and run the tests that way. So when we publish images we know everything is good

Oh yea I've tried them locally with the new tribes image just for them to work on gitactions the image needs to be updated because it pulls from the newest image in the automated PR actions

**Comment by Evanfeenstra** [comment]
> So theres something called openapi I think it may be worth checking out
> 
> I added a yml file here [0301db3](https://github.com/stakwork/sphinx-relay/pull/294/commits/0301db3addd24abab3ef9d6bec77b6bafa8124d3)
> 
> and here's a link to redoc which uses the openapi format https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/kevkevinpal/sphinx-relay/msg-channels/docs/deep/openapi.yml&nocors

nice! we should definitely eventually get every route in there. I like the swagger UI for OpenAPI https://swagger.io/tools/swaggerhub/

**Comment by kevkevinpal** [comment]
> > So theres something called openapi I think it may be worth checking out
> > I added a yml file here [0301db3](https://github.com/stakwork/sphinx-relay/pull/294/commits/0301db3addd24abab3ef9d6bec77b6bafa8124d3)
> > and here's a link to redoc which uses the openapi format https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/kevkevinpal/sphinx-relay/msg-channels/docs/deep/openapi.yml&nocors
> 
> nice! we should definitely eventually get every route in there. I like the swagger UI for OpenAPI https://swagger.io/tools/swaggerhub/

let me know what you think of the apidocs now it should be just the ones I've touched in this PR I can continue to update or open up bounties to get the other routes in there

**Comment by Evanfeenstra** [comment]
> > > So theres something called openapi I think it may be worth checking out
> > > I added a yml file here [0301db3](https://github.com/stakwork/sphinx-relay/pull/294/commits/0301db3addd24abab3ef9d6bec77b6bafa8124d3)
> > > and here's a link to redoc which uses the openapi format https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/kevkevinpal/sphinx-relay/msg-channels/docs/deep/openapi.yml&nocors
> > 
> > 
> > nice! we should definitely eventually get every route in there. I like the swagger UI for OpenAPI https://swagger.io/tools/swaggerhub/
> 
> let me know what you think of the apidocs now it should be just the ones I've touched in this PR I can continue to update or open up bounties to get the other routes in there

ya maybe lets do bounties for that, should be easy for a newbie

**Pull request merged**
