### PR TITLE
Clean up logs tags

### LINKED ISSUE #311: Clean up logs tags - $@ 300,000
`[Description]`

There are alot of logs that still have the second tag sitting there where we can just get rid of it

---

`[How to reproduce]`

in the relay repo run

`grep -nri --exclude-dir=node_modules --exclude-dir=dist "\[tribes\]" ./`

and we want to also remove `lightning` `db` `meme` `proxy` in addition to `tribes`

---

`[Acceptance Critera]`

Given I run this command in the relay repo `grep -nri --exclude-dir=node_modules --exclude-dir=dist "\[tribes\]" ./`
When I look at the logs
Then Nothing should show up
And repeat with these words `lightning` `db` `meme` `proxy` `tribes`

----
Some screenshots to what they look like

Screen Shot 2022-03-18 at 10 52 41 AM

Screen Shot 2022-03-18 at 11 08 02 AM

Screen Shot 2022-03-18 at 11 08 30 AM

### PR DESCRIPTION
**Pull request by antonilol**
fixes #311

@kevkevinpal is this what you meant by cleaning up, like removing the tags in the code and have logger.ts add the tags and date?

### CODE REVIEW

**Comment by kevkevinpal** [comment]
> fixes #311
> 
> @kevkevinpal is this what you meant by cleaning up, like removing the tags in the code and have logger.ts add the tags and date?

Yup exactly there are more spots that has logs like that if you run 
grep -nri --exclude-dir=node_modules --exclude-dir=dist "\[tribes\]" ./

you'll see them

and then also for these as well `lightning db meme proxy tribes`

**Comment by antonilol** [comment]
also cleaned up `[ssl]` log tags

**Comment by antonilol** [comment]
also cleaned up `[ssl]` log tags

**Review by kevkevinpal — APPROVED** [review]
Changes are looking good to me

**Pull request merged**
