### PR TITLE
Feat/add badge to tribe

### PR DESCRIPTION
**Pull request by tobi-bams**
### PR Summary

1. Created the add badge to tribe endpoint
2. Updated the badge bot logic to use the new mapping table instead of the meta field in the chat bot
3. Changed the `create` command for the badge bot to add and the logic also
4. Updated the badge bor test to accommodate the current badge workflow
5. Made a little change to the response returned by the create badge endpoint

### CODE REVIEW

**Review by Evanfeenstra — APPROVED** [review]
awesome!

**Comment by Evanfeenstra** [comment]
@tobi-bams `rewardType` and `rewardRequirement` need to be stored on the badge ALSO. These are "default values" when the Badge is added to the Tribe (the frontend will grab the defaults when pulling badges... you dont need to worry about copying the "default values" in the backend)

**Review by Evanfeenstra — APPROVED** [review]
looks great

**Review by kevkevinpal — APPROVED** [review]
LGTM 🚀

**Comment by kevkevinpal** [comment]
closing as this PR included these changes
https://github.com/stakwork/sphinx-relay/pull/593

**Comment by kevkevinpal** [comment]
ok this one can be closed

**Pull request closed without merging**
