### PR TITLE
using cors instead of preflightRequest attribute for socketio

### PR DESCRIPTION
**Pull request by kevkevinpal**
https://github.com/stakwork/sphinx-relay/issues/343

I think the issue was that the updated socketio doesn't allow cross origin by default so you need to manually say so, need to test this change before merging in

https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#cors-handling

Wonder if there's a way to test this in the socketio test

### CODE REVIEW

**Comment by Evanfeenstra** [comment]
From the docs it looks like `origin` should be set to `req.headers.origin`, not `true` ?

**Comment by kevkevinpal** [comment]
> From the docs it looks like `origin` should be set to `req.headers.origin`, not `true` ?

I was reading from here 
https://github.com/expressjs/cors#configuration-options

Where it says to use `true` when we want to use `req.headers("Origin")`

Otherwise I'm not sure where'd we get `req` from unless we can get it from the cors option

**Comment by Evanfeenstra** [comment]
> > From the docs it looks like `origin` should be set to `req.headers.origin`, not `true` ?
> 
> I was reading from here https://github.com/expressjs/cors#configuration-options
> 
> Where it says to use `true` when we want to use `req.headers("Origin")`
> 
> Otherwise I'm not sure where'd we get `req` from unless we can get it from the cors option

Got it. Can we merge this into a branch of `sphinx-relay`... so i can easily just update my live node and test?

**Comment by kevkevinpal** [comment]
> > > From the docs it looks like `origin` should be set to `req.headers.origin`, not `true` ?
> > 
> > 
> > I was reading from here https://github.com/expressjs/cors#configuration-options
> > Where it says to use `true` when we want to use `req.headers("Origin")`
> > Otherwise I'm not sure where'd we get `req` from unless we can get it from the cors option
> 
> Got it. Should be all good then. Can we merge this into a branch of `sphinx-relay`... so i can easily just update my live node and test?

Yea let me push it up and tell you which branch it is one sec

**Comment by kevkevinpal** [comment]
@Evanfeenstra it should be under this branch
https://github.com/stakwork/sphinx-relay/tree/socketIOCrossOrigin

**Comment by Evanfeenstra** [comment]
@kevkevinpal it works like a charm!

**Comment by Evanfeenstra** [comment]
Lets merge this one

**Pull request merged**
