### PR TITLE
Making the ports the same in Docker or Bare Metal

### PR DESCRIPTION
**Pull request by mishfit**
It doesn't look either the mac client win/linux or the iOS application are attempting to connect to port 3001.

### CODE REVIEW

**Comment by kevkevinpal** [comment]
So I think what might make more sense is to show the user how to change the port/validate which port to open rather than blindly using one or the other

for example we have the config file that is in `./config/app.json` which contains `node_http_protocol` `node_ip` and `node_http_port` 

where we have them being initialized in `./src/utils/config.ts`

**Comment by kevkevinpal** [comment]
did you resolve your issue by changing a setting in sphinx-relay?

**Comment by mishfit** [comment]
I searched for `3001` in all the client repos...nothing is trying to connect to `3001`. Swapping that out for port `3300` fixed things for me.

**Comment by antonilol** [comment]
> nothing is trying to connect to `3001`.

the port is not hardcoded, it is in the connection string when connecting for the first time with the qr code or can be configured

in the sphinx relay repo you can easily search with grep, just suppress the spam from node_modules
`grep -r --exclude-dir=node_modules 3001`

**Comment by kevkevinpal** [comment]
@mishfit if you take your connection string and run it through a base64 decoder you should be able to see where it's trying to connect to

**Comment by mishfit** [comment]
Perhaps the issue was something else, switching to 3300 appeared to solve it for me.

**Pull request closed without merging**
